zuul:
  sensitiveHeaders:
  ignored-services: '*'
  prefix: /api
  routes:
    reportservice:
      path: /report/**
    authserver:
      path: /auth/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true # 유레카 서비스에 자신을 등록
    fetchRegistry: true # 레즈스트리의 로컬 복사본 가져오게 허용
    serviceUrl: # 유레카 클러스터 구축
      defaultZone: http://j4c103.p.ssafy.io:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 5555

spring:
  application:
    name: zuulserver

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true # 유레카 서비스에 자신을 등록
#    fetchRegistry: true # 레즈스트리의 로컬 복사본 가져오게 허용
#    serviceUrl: # 유레카 클러스터 구축
#      defaultZone: http://localhost:8761/eureka/
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'